version: '3.8'
services:
  web:
    build: .
    image: modux:demo
    entrypoint: ./entrypoint.sh
    environment:
      - FLASK_APP=mondux
      - API_DB_HOST=pyth_db_1
    env_file:
      - api_database.env
    ports:
      - '5000:5000'
    volumes:
      - ./app/:/home/app
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    env_file:
      - api_database.env
    ports:
      - '5432:5432'
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/
