version: '3.8'
services:
  api:
    image: my-flask:latest
    ports: 
      - '5000:5000'
    environment:
      - FLASK_APP=flaskr
    volumes:
      - ./app/:/home/app
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - ./db/:/home
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local