#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username postgres <<-EOSQL
    CREATE USER $API_DB_USER with password '$API_DB_PASSWORD';
    CREATE DATABASE $API_DB;
    GRANT ALL PRIVILEGES ON DATABASE $API_DB TO $API_DB_USER;
EOSQL